### ISSUE TITLE
Nenhum dev vira sênior sem se viciar no mínimo em uma droga

### ISSUE THREAD

**Issue by Aurelioolive** [pilhacheia/tretadev#79]
O título já é bem óbvio.

**Comment by mariomeyrelles** [comment]
Se cafeína e açúcar também forem consideradas drogas, eu concordo.

**Comment by sergiocabral** [comment]
JavaScript também é droga?

**Comment by mariomeyrelles** [comment]
> 
> 
> JavaScript também é droga?

Sim. Trip ruim na maioria das vezes. Mas como qualquer outra droga, os usuários acabam sofrendo mais que os traficantes, que são os que mais enriquecem e ostentam em redes sociais carros, eletroeletrônicos caros e um padrão de vida incompatível com a renda declarada... rs

**Comment by Aurelioolive** [comment]
@mariomeyrelles pior que piramide

**Comment by terremoth** [comment]
Conheci um dev viciado em hinode
